version: '3.4'

services:
  express:
    image: call-center-signal-kafka-logical
    container_name: call-center-signal-kafka-logical
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes: 
      - $PWD/log/:/usr/src/app/log/